pages = [{"l":"index.html#","e":false,"i":"","n":"pgmq4s","t":"pgmq4s","d":"","k":"static","x":""},
{"l":"pgmq4s.html#","e":false,"i":"","n":"pgmq4s","t":"pgmq4s","d":"","k":"package","x":""},
{"l":"pgmq4s.html#MessageId-0","e":false,"i":"","n":"MessageId","t":"MessageId","d":"pgmq4s","k":"type","x":""},
{"l":"pgmq4s.html#QueueName-0","e":false,"i":"","n":"QueueName","t":"QueueName","d":"pgmq4s","k":"type","x":""},
{"l":"pgmq4s/Message.html#","e":false,"i":"","n":"Message","t":"Message[P, +H]","d":"pgmq4s","k":"enum","x":""},
{"l":"pgmq4s/Message$$Plain.html#","e":false,"i":"","n":"Plain","t":"Plain[A](msgId: MessageId, readCt: Int, enqueuedAt: OffsetDateTime, vt: OffsetDateTime, payload: A) extends Message[A, Nothing]","d":"pgmq4s.Message","k":"class","x":""},
{"l":"pgmq4s/Message$$WithHeaders.html#","e":false,"i":"","n":"WithHeaders","t":"WithHeaders[P, +H](msgId: MessageId, readCt: Int, enqueuedAt: OffsetDateTime, vt: OffsetDateTime, payload: P, headers: H)","d":"pgmq4s.Message","k":"class","x":""},
{"l":"pgmq4s/Message$$Plain.html#","e":false,"i":"","n":"Plain","t":"Plain[A](msgId: MessageId, readCt: Int, enqueuedAt: OffsetDateTime, vt: OffsetDateTime, payload: A) extends Message[A, Nothing]","d":"pgmq4s.Message","k":"class","x":""},
{"l":"pgmq4s/Message$$WithHeaders.html#","e":false,"i":"","n":"WithHeaders","t":"WithHeaders[P, +H](msgId: MessageId, readCt: Int, enqueuedAt: OffsetDateTime, vt: OffsetDateTime, payload: P, headers: H)","d":"pgmq4s.Message","k":"class","x":""},
{"l":"pgmq4s/MessageId$.html#","e":false,"i":"","n":"MessageId","t":"MessageId","d":"pgmq4s","k":"object","x":""},
{"l":"pgmq4s/MessageId$.html#apply-fffff788","e":false,"i":"","n":"apply","t":"apply(id: Long): MessageId","d":"pgmq4s.MessageId","k":"def","x":""},
{"l":"pgmq4s/MessageId$.html#value-fffff788","e":false,"i":"extension (id: MessageId)","n":"value","t":"value: Long","d":"pgmq4s.MessageId","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#","e":false,"i":"","n":"PgmqAdmin","t":"PgmqAdmin[F[_]] extends PgmqAdminBackend[F]","d":"pgmq4s","k":"trait","x":""},
{"l":"pgmq4s/PgmqAdmin.html#createPartitionedQueue-c2","e":false,"i":"","n":"createPartitionedQueue","t":"createPartitionedQueue(queue: QueueName, partitionInterval: String, retentionInterval: String): F[Unit]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#createQueue-fffff5f8","e":false,"i":"","n":"createQueue","t":"createQueue(queue: QueueName): F[Unit]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#detachArchive-fffff5f8","e":false,"i":"","n":"detachArchive","t":"detachArchive(queue: QueueName): F[Unit]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#dropQueue-fffff5f8","e":false,"i":"","n":"dropQueue","t":"dropQueue(queue: QueueName): F[Boolean]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#listQueues-0","e":false,"i":"","n":"listQueues","t":"listQueues: F[List[QueueInfo]]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#metrics-fffff5f8","e":false,"i":"","n":"metrics","t":"metrics(queue: QueueName): F[Option[QueueMetrics]]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#metricsAll-0","e":false,"i":"","n":"metricsAll","t":"metricsAll: F[List[QueueMetrics]]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdmin.html#purgeQueue-fffff5f8","e":false,"i":"","n":"purgeQueue","t":"purgeQueue(queue: QueueName): F[Long]","d":"pgmq4s.PgmqAdmin","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#","e":false,"i":"","n":"PgmqAdminBackend","t":"PgmqAdminBackend[F[_]]","d":"pgmq4s","k":"trait","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#createPartitionedQueueRaw-c2","e":false,"i":"","n":"createPartitionedQueueRaw","t":"createPartitionedQueueRaw(queue: String, partitionInterval: String, retentionInterval: String): F[Unit]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#createQueueRaw-fffff5f8","e":false,"i":"","n":"createQueueRaw","t":"createQueueRaw(queue: String): F[Unit]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#detachArchiveRaw-fffff5f8","e":false,"i":"","n":"detachArchiveRaw","t":"detachArchiveRaw(queue: String): F[Unit]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#dropQueueRaw-fffff5f8","e":false,"i":"","n":"dropQueueRaw","t":"dropQueueRaw(queue: String): F[Boolean]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#listQueuesRaw-0","e":false,"i":"","n":"listQueuesRaw","t":"listQueuesRaw: F[List[QueueInfo]]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#metricsAllRaw-0","e":false,"i":"","n":"metricsAllRaw","t":"metricsAllRaw: F[List[QueueMetrics]]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#metricsRaw-fffff5f8","e":false,"i":"","n":"metricsRaw","t":"metricsRaw(queue: String): F[Option[QueueMetrics]]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqAdminBackend.html#purgeQueueRaw-fffff5f8","e":false,"i":"","n":"purgeQueueRaw","t":"purgeQueueRaw(queue: String): F[Long]","d":"pgmq4s.PgmqAdminBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#","e":false,"i":"","n":"PgmqBackend","t":"PgmqBackend[F[_]]","d":"pgmq4s","k":"trait","x":""},
{"l":"pgmq4s/PgmqBackend.html#archiveBatchRaw-8e0","e":false,"i":"","n":"archiveBatchRaw","t":"archiveBatchRaw(queue: String, msgIds: List[Long]): F[List[Long]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#archiveRaw-9fc","e":false,"i":"","n":"archiveRaw","t":"archiveRaw(queue: String, msgId: Long): F[Boolean]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#deleteBatchRaw-8e0","e":false,"i":"","n":"deleteBatchRaw","t":"deleteBatchRaw(queue: String, msgIds: List[Long]): F[List[Long]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#deleteRaw-9fc","e":false,"i":"","n":"deleteRaw","t":"deleteRaw(queue: String, msgId: Long): F[Boolean]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#popRaw-fffff5f8","e":false,"i":"","n":"popRaw","t":"popRaw(queue: String): F[Option[RawMessage]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#readRaw-fffff298","e":false,"i":"","n":"readRaw","t":"readRaw(queue: String, vt: Int, qty: Int): F[List[RawMessage]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendBatchRaw-8e0","e":false,"i":"","n":"sendBatchRaw","t":"sendBatchRaw(queue: String, bodies: List[String]): F[List[Long]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendBatchRaw-fffff20d","e":false,"i":"","n":"sendBatchRaw","t":"sendBatchRaw(queue: String, bodies: List[String], delay: Int): F[List[Long]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendBatchRaw-fffff8f8","e":false,"i":"","n":"sendBatchRaw","t":"sendBatchRaw(queue: String, bodies: List[String], headers: List[String]): F[List[Long]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendBatchRaw-fffffcf5","e":false,"i":"","n":"sendBatchRaw","t":"sendBatchRaw(queue: String, bodies: List[String], headers: List[String], delay: Int): F[List[Long]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendRaw-fffff85d","e":false,"i":"","n":"sendRaw","t":"sendRaw(queue: String, body: String): F[Long]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendRaw-f30","e":false,"i":"","n":"sendRaw","t":"sendRaw(queue: String, body: String, delay: Int): F[Long]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendRaw-c2","e":false,"i":"","n":"sendRaw","t":"sendRaw(queue: String, body: String, headers: String): F[Long]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#sendRaw-fffff86b","e":false,"i":"","n":"sendRaw","t":"sendRaw(queue: String, body: String, headers: String, delay: Int): F[Long]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqBackend.html#setVtRaw-71","e":false,"i":"","n":"setVtRaw","t":"setVtRaw(queue: String, msgId: Long, vtOffset: Int): F[Option[RawMessage]]","d":"pgmq4s.PgmqBackend","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#","e":false,"i":"","n":"PgmqClient","t":"PgmqClient[F[_]] extends PgmqBackend[F]","d":"pgmq4s","k":"trait","x":""},
{"l":"pgmq4s/PgmqClient.html#archive-9fc","e":false,"i":"","n":"archive","t":"archive(queue: QueueName, msgId: MessageId): F[Boolean]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#archiveBatch-8e0","e":false,"i":"","n":"archiveBatch","t":"archiveBatch(queue: QueueName, msgIds: List[MessageId]): F[List[MessageId]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#delete-9fc","e":false,"i":"","n":"delete","t":"delete(queue: QueueName, msgId: MessageId): F[Boolean]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#deleteBatch-8e0","e":false,"i":"","n":"deleteBatch","t":"deleteBatch(queue: QueueName, msgIds: List[MessageId]): F[List[MessageId]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#pop-a5e","e":false,"i":"","n":"pop","t":"pop[P : PgmqDecoder](queue: QueueName): F[Option[Plain[P]]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#pop-ed4","e":false,"i":"","n":"pop","t":"pop[P : PgmqDecoder, H : PgmqDecoder](queue: QueueName): F[Option[Message[P, H]]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#read-4be","e":false,"i":"","n":"read","t":"read[P : PgmqDecoder](queue: QueueName, vt: Int, qty: Int): F[List[Plain[P]]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#read-2f4","e":false,"i":"","n":"read","t":"read[P : PgmqDecoder, H : PgmqDecoder](queue: QueueName, vt: Int, qty: Int): F[List[Message[P, H]]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#send-c09","e":false,"i":"","n":"send","t":"send[P](queue: QueueName, message: P)(using enc: PgmqEncoder[P]): F[MessageId]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#send-7be","e":false,"i":"","n":"send","t":"send[P](queue: QueueName, message: P, delay: Int)(using enc: PgmqEncoder[P]): F[MessageId]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#send-4aa","e":false,"i":"","n":"send","t":"send[P, H](queue: QueueName, message: P, headers: H)(using encP: PgmqEncoder[P], encH: PgmqEncoder[H]): F[MessageId]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#send-477","e":false,"i":"","n":"send","t":"send[P, H](queue: QueueName, message: P, headers: H, delay: Int)(using encP: PgmqEncoder[P], encH: PgmqEncoder[H]): F[MessageId]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#sendBatch-fffffa1c","e":false,"i":"","n":"sendBatch","t":"sendBatch[P](queue: QueueName, messages: List[P])(using enc: PgmqEncoder[P]): F[List[MessageId]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#sendBatch-f0b","e":false,"i":"","n":"sendBatch","t":"sendBatch[P](queue: QueueName, messages: List[P], delay: Int)(using enc: PgmqEncoder[P]): F[List[MessageId]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#sendBatch-204","e":false,"i":"","n":"sendBatch","t":"sendBatch[P, H](queue: QueueName, messages: List[P], headers: List[H])(using encP: PgmqEncoder[P], encH: PgmqEncoder[H]): F[List[MessageId]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#sendBatch-c5d","e":false,"i":"","n":"sendBatch","t":"sendBatch[P, H](queue: QueueName, messages: List[P], headers: List[H], delay: Int)(using encP: PgmqEncoder[P], encH: PgmqEncoder[H]): F[List[MessageId]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#setVt-515","e":false,"i":"","n":"setVt","t":"setVt[P : PgmqDecoder](queue: QueueName, msgId: MessageId, vtOffset: Int): F[Option[Plain[P]]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqClient.html#setVt-fffff129","e":false,"i":"","n":"setVt","t":"setVt[P : PgmqDecoder, H : PgmqDecoder](queue: QueueName, msgId: MessageId, vtOffset: Int): F[Option[Message[P, H]]]","d":"pgmq4s.PgmqClient","k":"def","x":""},
{"l":"pgmq4s/PgmqCodec.html#","e":false,"i":"","n":"PgmqCodec","t":"PgmqCodec[A] extends PgmqEncoder[A], PgmqDecoder[A]","d":"pgmq4s","k":"trait","x":""},
{"l":"pgmq4s/PgmqCodec$.html#","e":false,"i":"","n":"PgmqCodec","t":"PgmqCodec","d":"pgmq4s","k":"object","x":""},
{"l":"pgmq4s/PgmqCodec$.html#from-fffff47a","e":false,"i":"","n":"from","t":"from[A](enc: PgmqEncoder[A], dec: PgmqDecoder[A]): PgmqCodec[A]","d":"pgmq4s.PgmqCodec","k":"def","x":""},
{"l":"pgmq4s/PgmqDecoder.html#","e":false,"i":"","n":"PgmqDecoder","t":"PgmqDecoder[A]","d":"pgmq4s","k":"trait","x":""},
{"l":"pgmq4s/PgmqDecoder.html#decode-fffffbe4","e":false,"i":"","n":"decode","t":"decode(json: String): Either[Throwable, A]","d":"pgmq4s.PgmqDecoder","k":"def","x":""},
{"l":"pgmq4s/PgmqDecoder.html#emap-7f5","e":false,"i":"","n":"emap","t":"emap[B](f: A => Either[Throwable, B]): PgmqDecoder[B]","d":"pgmq4s.PgmqDecoder","k":"def","x":""},
{"l":"pgmq4s/PgmqDecoder.html#map-7f5","e":false,"i":"","n":"map","t":"map[B](f: A => B): PgmqDecoder[B]","d":"pgmq4s.PgmqDecoder","k":"def","x":""},
{"l":"pgmq4s/PgmqDecoder$.html#","e":false,"i":"","n":"PgmqDecoder","t":"PgmqDecoder","d":"pgmq4s","k":"object","x":""},
{"l":"pgmq4s/PgmqDecoder$.html#given_PgmqDecoder_String-0","e":false,"i":"","n":"given_PgmqDecoder_String","t":"given_PgmqDecoder_String: PgmqDecoder[String]","d":"pgmq4s.PgmqDecoder","k":"given","x":""},
{"l":"pgmq4s/PgmqDecoder$.html#instance-7f5","e":false,"i":"","n":"instance","t":"instance[A](f: String => Either[Throwable, A]): PgmqDecoder[A]","d":"pgmq4s.PgmqDecoder","k":"def","x":""},
{"l":"pgmq4s/PgmqEncoder.html#","e":false,"i":"","n":"PgmqEncoder","t":"PgmqEncoder[A]","d":"pgmq4s","k":"trait","x":""},
{"l":"pgmq4s/PgmqEncoder.html#contramap-cd","e":false,"i":"","n":"contramap","t":"contramap[B](f: B => A): PgmqEncoder[B]","d":"pgmq4s.PgmqEncoder","k":"def","x":""},
{"l":"pgmq4s/PgmqEncoder.html#encode-9f8","e":false,"i":"","n":"encode","t":"encode(value: A): String","d":"pgmq4s.PgmqEncoder","k":"def","x":""},
{"l":"pgmq4s/PgmqEncoder$.html#","e":false,"i":"","n":"PgmqEncoder","t":"PgmqEncoder","d":"pgmq4s","k":"object","x":""},
{"l":"pgmq4s/PgmqEncoder$.html#given_PgmqEncoder_String-0","e":false,"i":"","n":"given_PgmqEncoder_String","t":"given_PgmqEncoder_String: PgmqEncoder[String]","d":"pgmq4s.PgmqEncoder","k":"given","x":""},
{"l":"pgmq4s/PgmqEncoder$.html#instance-cd","e":false,"i":"","n":"instance","t":"instance[A](f: A => String): PgmqEncoder[A]","d":"pgmq4s.PgmqEncoder","k":"def","x":""},
{"l":"pgmq4s/QueueInfo.html#","e":false,"i":"","n":"QueueInfo","t":"QueueInfo(queueName: QueueName, isPartitioned: Boolean, isUnlogged: Boolean, createdAt: OffsetDateTime)","d":"pgmq4s","k":"class","x":""},
{"l":"pgmq4s/QueueMetrics.html#","e":false,"i":"","n":"QueueMetrics","t":"QueueMetrics(queueName: QueueName, queueLength: Long, newestMsgAgeSec: Option[Long], oldestMsgAgeSec: Option[Long], totalMessages: Long, scrapeTime: OffsetDateTime)","d":"pgmq4s","k":"class","x":""},
{"l":"pgmq4s/QueueName$.html#","e":false,"i":"","n":"QueueName","t":"QueueName","d":"pgmq4s","k":"object","x":""},
{"l":"pgmq4s/QueueName$.html#apply-fffff2ca","e":false,"i":"","n":"apply","t":"apply(name: String): QueueName","d":"pgmq4s.QueueName","k":"def","x":""},
{"l":"pgmq4s/QueueName$.html#value-fffff2ca","e":false,"i":"extension (q: QueueName)","n":"value","t":"value: String","d":"pgmq4s.QueueName","k":"def","x":""},
{"l":"pgmq4s/RawMessage.html#","e":false,"i":"","n":"RawMessage","t":"RawMessage(msgId: Long, readCt: Int, enqueuedAt: OffsetDateTime, vt: OffsetDateTime, message: String, headers: Option[String])","d":"pgmq4s","k":"class","x":""},
{"l":"docs/index.html#","e":false,"i":"","n":"pgmq4s","t":"pgmq4s","d":"","k":"static","x":""},
{"l":"docs/index.html#","e":false,"i":"","n":"Overview","t":"Overview","d":"","k":"static","x":""},
{"l":"docs/quick-example.html#","e":false,"i":"","n":"Quick Example","t":"Quick Example","d":"","k":"static","x":""},
{"l":"docs/installation.html#","e":false,"i":"","n":"Installation","t":"Installation","d":"","k":"static","x":""},
{"l":"docs/api-coverage.html#","e":false,"i":"","n":"API Coverage","t":"API Coverage","d":"","k":"static","x":""},
{"l":"docs/json-codecs.html#","e":false,"i":"","n":"JSON Codecs","t":"JSON Codecs","d":"","k":"static","x":""},
{"l":"docs/backends/index.html#","e":false,"i":"","n":"Backends","t":"Backends","d":"","k":"static","x":""},
{"l":"docs/backends/doobie.html#","e":false,"i":"","n":"Doobie","t":"Doobie","d":"","k":"static","x":""},
{"l":"docs/backends/skunk.html#","e":false,"i":"","n":"Skunk","t":"Skunk","d":"","k":"static","x":""},
{"l":"docs/backends/anorm.html#","e":false,"i":"","n":"Anorm","t":"Anorm","d":"","k":"static","x":""},
{"l":"docs/backends/slick.html#","e":false,"i":"","n":"Slick","t":"Slick","d":"","k":"static","x":""}];