name = "pgmq4s"
organization = "io.github.matejcerny"
scalaVersion = "3.3.7"
scalacOptions = [
  "-encoding", "utf8",
  "-deprecation",
  "-feature",
  "-unchecked",
  "-Wunused:all",
  "-Wvalue-discard"
]
